### PR TITLE
NetworkManager instead of Netplan

### PR DESCRIPTION
**Pull request by ghost**
NetworkManager is a wee bit easier to work with (IMO), so I added some docs for using NetworkManager instead of Netplan.

### CODE REVIEW

**Comment by Aksel-Rasmussen** [comment]
lgtm as long as you've tested it

**Comment by ABoiGoE** [comment]
Intruiging

**Review by ABoiGoE — APPROVED** [review]
very very interesting

**Review by Aksel-Rasmussen — APPROVED** [review]
lgtm

**Pull request merged**
